# Generated by Django 5.0.4 on 2024-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorymodel_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(max_length=30),
        ),
    ]
