# Generated by Django 5.0.4 on 2024-04-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_categorymodel_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
