# Generated by Django 5.0.4 on 2024-04-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.categorymodel'),
        ),
    ]
