# Generated by Django 5.0.4 on 2024-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productsmodel_category_productsmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='test',
            field=models.IntegerField(null=True),
        ),
    ]
