# Generated by Django 5.0.4 on 2024-04-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productsmodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='test',
        ),
    ]
